name:               delude
version:            0.1.0.3
synopsis:           Simple Prelude replacement for toy programs
description:        See https://github.com/chuahou/delude#readme.
category:           Development
github:             chuahou/delude
author:             Chua Hou
maintainer:         human+github@chuahou.dev
extra-source-files: CHANGELOG.md

ghc-options:
    - -Wall
    - -fwarn-incomplete-uni-patterns
    - -fwarn-incomplete-record-updates

default-extensions:
    - NoImplicitPrelude

dependencies:
    - base >= 4.13 && < 5

library:
    source-dirs: src

tests:
    test:
        main:        Spec.hs
        source-dirs: test
        dependencies:
            - delude
            - hspec      ^>= 2.7.2
            - QuickCheck ^>= 2.13.2
        default-extensions:
            - ScopedTypeVariables
