name: "nix test"
on:
    pull_request:
    push:
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.4.0
        - uses: cachix/install-nix-action@v15
        - uses: cachix/cachix-action@v10
          with:
              name: chuahou
              authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        - run: nix build
        - run: nix develop -c sh -c 'hpack | grep "up-to-date"'
