name: "nix test"
on:
    pull_request:
    push:
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2.3.4
        - uses: cachix/install-nix-action@v12
        - uses: cachix/cachix-action@v8
          with:
              name: chuahou
              authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        - run: nix-build
        - run: nix-shell --run 'hpack | grep "up-to-date"'
